In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("player_mvp_stats.csv")

In [3]:
data

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14088,14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14089,14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14090,14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14091,14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11817 entries, 0 to 14091
Data columns (total 42 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  11817 non-null  int64
 1   Player      11817 non-null  object
 2   Pos         11817 non-null  object
 3   Age         11817 non-null  int64
 4   Tm          11817 non-null  object
 5   G           11817 non-null  int64
 6   GS          11817 non-null  int64
 7   MP          11817 non-null  float64
 8   FG          11817 non-null  float64
 9   FGA         11817 non-null  float64
 10  FG%         11817 non-null  float64
 11  3P          11817 non-null  float64
 12  3PA         11817 non-null  float64
 13  3P%         11817 non-null  float64
 14  2P          11817 non-null  float64
 15  2PA         11817 non-null  float64
 16  2P%         11817 non-null  float64
 17  eFG%        11817 non-null  float64
 18  FT          11817 non-null  float64
 19  FTA         11817 non-null  float64
 20  FT%         11817 non-null  float64
 21  ORB         11817 non-null  float64
 22  DRB         11817 non-null  float64
 23  TRB         11817 non-null  float64
 24  AST         11817 non-null  float64
 25  STL         11817 non-null  float64
 26  BLK         11817 non-null  float64
 27  TOV         11817 non-null  float64
 28  PF          11817 non-null  float64
 29  PTS         11817 non-null  float64
 30  Year        11817 non-null  int64
 31  Pts Won     11817 non-null  float64
 32  Pts Max     11817 non-null  float64
 33  Share       11817 non-null  float64
 34  Team        11817 non-null  object
 35  W           11817 non-null  int64
 36  L           11817 non-null  int64
 37  W/L%        11817 non-null  float64
 38  GB          11817 non-null  float64
 39  PS/G        11817 non-null  float64
 40  PA/G        11817 non-null  float64
 41  SRS         11817 non-null  float64
dtypes: float64(31), int64(7), object(4)
memory usage: 3.9+ MB

In [8]:
data.columns

Index(['Unnamed: 0', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG',
       'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT',
       'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'Year', 'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%',
       'GB', 'PS/G', 'PA/G', 'SRS'],
      dtype='object')

In [9]:
del data["Unnamed: 0"]

In [10]:
data.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [17]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
        'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS']

In [18]:
train_data = data[data["Year"] < 2021]

In [19]:
test_data = data[data["Year"] == 2021]

In [20]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [21]:
reg.fit(train_data[predictors], train_data["Share"])

Ridge(alpha=0.1)

Ridge(alpha=0.1)

In [22]:
predictions = reg.predict(test_data[predictors])

In [24]:
predictions = pd.DataFrame(predictions, columns=["predictions"], index = test_data.index )

In [25]:
predictions

       predictions
630       0.013211
631      -0.015243
632       0.002721
633      -0.004205
635      -0.006408
...            ...
13897    -0.014080
13898    -0.016109
13899     0.016120
13900    -0.024304
13901    -0.007633

[503 rows x 1 columns]

In [26]:
combination = pd.concat([test_data[["Player", "Share"]], predictions], axis=1)

In [27]:
combination

                       Player  Share  predictions
630              Aaron Gordon    0.0     0.013211
631             Austin Rivers    0.0    -0.015243
632                   Bol Bol    0.0     0.002721
633          Facundo Campazzo    0.0    -0.004205
635            JaMychal Green    0.0    -0.006408
...                       ...    ...          ...
13897             Patty Mills    0.0    -0.014080
13898  Quinndary Weatherspoon    0.0    -0.016109
13899                Rudy Gay    0.0     0.016120
13900               Tre Jones    0.0    -0.024304
13901              Trey Lyles    0.0    -0.007633

[503 rows x 3 columns]

In [28]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  predictions
641             Nikola Jokić  0.961     0.177117
8624             Joel Embiid  0.580     0.178830
3651           Stephen Curry  0.449     0.158642
9907   Giannis Antetokounmpo  0.345     0.230360
1389              Chris Paul  0.138     0.077143
10997            Luka Dončić  0.042     0.162990
7464          Damian Lillard  0.038     0.126132
3536           Julius Randle  0.020     0.093348
3531            Derrick Rose  0.010     0.034894
11358            Rudy Gobert  0.008     0.101273

In [29]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.0028773911136404603

In [30]:
combination["Share"].value_counts()

0.000    488
0.001      3
0.961      1
0.138      1
0.010      1
0.020      1
0.449      1
0.005      1
0.038      1
0.003      1
0.580      1
0.345      1
0.042      1
0.008      1
Name: Share, dtype: int64

In [33]:
combination = combination.sort_values("Share", ascending=False)
combination["Rank"] = list(range(1, combination.shape[0] + 1))

In [34]:
combination.head(10)

                      Player  Share  predictions  Rk  Rank
641             Nikola Jokić  0.961     0.177117   1     1
8624             Joel Embiid  0.580     0.178830   2     2
3651           Stephen Curry  0.449     0.158642   3     3
9907   Giannis Antetokounmpo  0.345     0.230360   4     4
1389              Chris Paul  0.138     0.077143   5     5
10997            Luka Dončić  0.042     0.162990   6     6
7464          Damian Lillard  0.038     0.126132   7     7
3536           Julius Randle  0.020     0.093348   8     8
3531            Derrick Rose  0.010     0.034894   9     9
11358            Rudy Gobert  0.008     0.101273  10    10

In [35]:
combination = combination.sort_values("predictions", ascending=False)
combination["Predicted_Rank"] = list(range(1, combination.shape[0] + 1))

In [36]:
combination.head(10)

                      Player  Share  predictions   Rk  Rank  Predicted_Rank
9907   Giannis Antetokounmpo  0.345     0.230360    4     4               1
8624             Joel Embiid  0.580     0.178830    2     2               2
641             Nikola Jokić  0.961     0.177117    1     1               3
10997            Luka Dončić  0.042     0.162990    6     6               4
3736            LeBron James  0.001     0.161833   14    13               5
4177            Kevin Durant  0.000     0.159016  497   175               6
3651           Stephen Curry  0.449     0.158642    3     3               7
4174            James Harden  0.001     0.149270   15    14               8
11784        Zion Williamson  0.000     0.149048  236   436               9
5328           Kawhi Leonard  0.001     0.127128   13    15              10

In [37]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  predictions  Rk  Rank  Predicted_Rank
641             Nikola Jokić  0.961     0.177117   1     1               3
8624             Joel Embiid  0.580     0.178830   2     2               2
3651           Stephen Curry  0.449     0.158642   3     3               7
9907   Giannis Antetokounmpo  0.345     0.230360   4     4               1
1389              Chris Paul  0.138     0.077143   5     5              33
10997            Luka Dončić  0.042     0.162990   6     6               4
7464          Damian Lillard  0.038     0.126132   7     7              12
3536           Julius Randle  0.020     0.093348   8     8              26
3531            Derrick Rose  0.010     0.034894   9     9              74
11358            Rudy Gobert  0.008     0.101273  10    10              21

In [51]:
def find_ap(combination):
    
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("Share", ascending=False)
    
    ps = []
    
    found = 0
    seen = 1
    
    for index, row in predicted.iterrows():
        
        if row["Player"] in actual["Player"].values:
            found +=1
            ps.append(found/seen)
        seen +=1 
    return sum(ps) / len(ps)

In [41]:
find_ap(combination)

1.0

In [48]:
years = list(range(1991,2022))

In [53]:
aps = []
all_predictions = []
for year in years[5:]:
    train_data = data[data["Year"] < year]
    test_data = data[data["Year"] == year]
    
    reg.fit(train_data[predictors], train_data["Share"])
    predictions = reg.predict(test_data[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index = test_data.index )
    combination = pd.concat([test_data[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [54]:
sum(aps) / len(aps)

1.0

In [63]:
def add_ranks(combination):
    
    combination = combination.sort_values("Share", ascending=False)
    combination["Rank"] = list(range(1, combination.shape[0] + 1))
    combination = combination.sort_values("predictions", ascending=False)
    combination["Predicted_Rank"] = list(range(1, combination.shape[0] + 1))
    combination["Diff"] = combination["Rank"] - combination["Predicted_Rank"]
    
    return combination

In [66]:
ranking = add_ranks(all_predictions[1])
ranking[ranking["Rank"] < 6].sort_values("Diff", ascending=False)

               Player  Share  predictions  Rank  Predicted_Rank  Diff
1600      Karl Malone  0.857     0.213136     1               1     0
10524  Michael Jordan  0.832     0.183358     2               3    -1
908        Grant Hill  0.327     0.133309     3               5    -2
4682     Tim Hardaway  0.207     0.061597     4              22   -18
8248        Glen Rice  0.117     0.039500     5              45   -40

In [70]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train_data = data[data["Year"] < year]
        test_data = data[data["Year"] == year]
        model.fit(train_data[predictors],train_data["Share"])
        predictions = model.predict(test_data[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test_data.index)
        combination = pd.concat([test_data[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [71]:
mean_ap, aps, all_predictions = backtest(data, reg, years[5:], predictors)

In [72]:
mean_ap

1.0